# Generated by Django 4.2.9 on 2026-10-02 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='预约开始时间')),
                ('end_time', models.DateTimeField(verbose_name='预约结束时间')),
                ('status', models.CharField(choices=[('confirmed', '已确认'), ('cancelled', '已取消'), ('completed', '已完成')], default='confirmed', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'ac_appointment',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=64, unique=True, verbose_name='案件编号')),
                ('name', models.CharField(max_length=200, verbose_name='案件名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在办')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'db_table': 'ac_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAppraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('organization', models.CharField(max_length=200, verbose_name='鉴定机构')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在册')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'external'}, on_delete=django.db.models.deletion.PROTECT, related_name='appraiser_profile', to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '外部鉴定人员',
                'verbose_name_plural': '外部鉴定人员',
                'db_table': 'ac_external_appraiser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='access_control.appointment', verbose_name='关联预约')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='access_control.externalappraiser', verbose_name='被授权人')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='access_control.case', verbose_name='授权案件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_grants', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
            ],
            options={
                'verbose_name': '临时授权',
                'verbose_name_plural': '临时授权',
                'db_table': 'ac_grant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('basis_type', models.CharField(max_length=50, verbose_name='依据类型')),
                ('basis_ref', models.CharField(max_length=200, verbose_name='依据文号')),
                ('basis_reason', models.TextField(verbose_name='授权依据说明')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_to', models.DateTimeField(verbose_name='失效时间')),
                ('scope_evidence_ids', models.JSONField(default=list, verbose_name='资源范围快照')),
                ('status', models.CharField(choices=[('active', '生效中'), ('superseded', '已换发'), ('revoked', '已撤销')], default='active', max_length=20, verbose_name='状态')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='签发时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='access_control.grant', verbose_name='所属授权')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_grant_versions', to=settings.AUTH_USER_MODEL, verbose_name='签发人')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_grant_versions', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
            ],
            options={
                'verbose_name': '授权版本',
                'verbose_name_plural': '授权版本',
                'db_table': 'ac_grant_version',
                'ordering': ['grant_id', '-version_no'],
                'unique_together': {('grant', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='access_control.case', verbose_name='所属案件')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_evidences', to='warehouse.goods', verbose_name='物资')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_evidences', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '在案物资',
                'verbose_name_plural': '在案物资',
                'db_table': 'ac_case_evidence',
                'unique_together': {('case', 'goods')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='access_control.externalappraiser', verbose_name='鉴定人员'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='access_control.case', verbose_name='预约案件'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='预约确认人'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='evidences',
            field=models.ManyToManyField(related_name='appointments', to='access_control.caseevidence', verbose_name='预约查看物资'),
        ),
        migrations.CreateModel(
            name='AccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraiser_name', models.CharField(max_length=50, verbose_name='鉴定人员姓名快照')),
                ('grant_version_no', models.PositiveIntegerField(null=True, verbose_name='放行授权版本号')),
                ('result', models.CharField(choices=[('allowed', '放行'), ('denied', '拒绝')], max_length=10, verbose_name='判定结论')),
                ('deny_reason', models.CharField(blank=True, choices=[('not_appraiser', '账号非外部鉴定人员'), ('appraiser_inactive', '鉴定人员档案已停用'), ('no_appointment', '无有效预约'), ('appointment_outside_window', '不在预约时段内'), ('appointment_cancelled', '预约已取消'), ('no_active_grant', '无生效授权'), ('grant_outside_window', '授权不在生效区间内'), ('grant_revoked', '授权已被提前撤销'), ('out_of_scope', '资源不在授权范围内'), ('evidence_not_in_case', '物资不属于授权案件')], max_length=40, verbose_name='拒绝原因')),
                ('accessed_at', models.DateTimeField(default=None, verbose_name='访问时刻')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='用户代理')),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='access_control.appointment', verbose_name='匹配预约')),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='access_control.externalappraiser', verbose_name='鉴定人员')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='access_control.case', verbose_name='案件')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='access_control.caseevidence', verbose_name='访问物资')),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='access_control.grant', verbose_name='匹配授权')),
                ('grant_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='access_control.grantversion', verbose_name='放行授权版本')),
            ],
            options={
                'verbose_name': '授权访问审计',
                'verbose_name_plural': '授权访问审计',
                'db_table': 'ac_access_audit',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
