# Generated by Django 4.2.9 on 2026-10-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', '超级管理员'), ('admin', '管理员'), ('user', '普通用户'), ('external', '外部鉴定人员')], default='user', max_length=20, verbose_name='角色'),
        ),
    ]
