# Generated by Django 4.2.9 on 2026-10-02 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_no', models.CharField(db_index=True, max_length=30, verbose_name='授权编号')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('reason', models.TextField(verbose_name='授权依据')),
                ('effective_from', models.DateTimeField(verbose_name='生效时间')),
                ('effective_until', models.DateTimeField(verbose_name='失效时间')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='被取代时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.CharField(blank=True, max_length=500, verbose_name='撤销原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '临时授权',
                'verbose_name_plural': '临时授权',
                'db_table': 'authz_temporary_grant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryGrantScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_grant_scopes', to='warehouse.goods', verbose_name='物资')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='authorization.temporarygrant', verbose_name='授权版本')),
            ],
            options={
                'verbose_name': '授权资源范围',
                'verbose_name_plural': '授权资源范围',
                'db_table': 'authz_grant_scope',
                'unique_together': {('grant', 'goods')},
            },
        ),
        migrations.AddField(
            model_name='temporarygrant',
            name='goods',
            field=models.ManyToManyField(related_name='temporary_grants', through='authorization.TemporaryGrantScope', to='warehouse.goods', verbose_name='授权物资范围'),
        ),
        migrations.AddField(
            model_name='temporarygrant',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_temporary_grants', to=settings.AUTH_USER_MODEL, verbose_name='授权人'),
        ),
        migrations.AddField(
            model_name='temporarygrant',
            name='grantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_grants', to=settings.AUTH_USER_MODEL, verbose_name='被授权人'),
        ),
        migrations.AddField(
            model_name='temporarygrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_temporary_grants', to=settings.AUTH_USER_MODEL, verbose_name='撤销人'),
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='访问账号')),
                ('goods_code', models.CharField(max_length=50, verbose_name='物资编码')),
                ('goods_name', models.CharField(max_length=200, verbose_name='物资名称')),
                ('grant_no', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='命中授权编号')),
                ('grant_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='命中授权版本号')),
                ('decision', models.CharField(choices=[('allowed', '放行'), ('denied', '拒绝')], max_length=10, verbose_name='访问结论')),
                ('basis', models.CharField(blank=True, choices=[('role', '角色权限'), ('grant', '临时授权')], max_length=10, verbose_name='放行依据')),
                ('deny_reason', models.CharField(blank=True, max_length=30, verbose_name='拒绝原因')),
                ('deny_detail', models.CharField(blank=True, max_length=200, verbose_name='拒绝说明')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='访问路径')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_logs', to='warehouse.goods', verbose_name='访问物资')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_audit_logs', to='authorization.temporarygrant', verbose_name='命中授权版本')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
            ],
            options={
                'verbose_name': '访问审计记录',
                'verbose_name_plural': '访问审计记录',
                'db_table': 'authz_access_audit_log',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='temporarygrant',
            unique_together={('grant_no', 'version')},
        ),
    ]
